// Generated by scripts/generate-viewer-contracts.ts from contracts/viewer.asyncapi.json.
import { z } from "zod/v4";

export const VIEWER_PROTOCOL_VERSION = 1;
export const viewerClientMessage = z.discriminatedUnion("type", [
	z.object({
		type: z.literal("hello"),
		protocol: z.number().int().positive(),
		subscriptions: z.array(z.enum(["catalog", "executions"])),
		cursors: z.record(z.string(), z.number().int().nonnegative()).default({}),
	}),
]);
export type ViewerClientMessage = z.output<typeof viewerClientMessage>;
