// Generated by scripts/generate-viewer-contracts.ts from contracts/viewer.openapi.json.
type ExecutionRequest = ({ testId: string } | { testIds: string[] } | { all: true }) & {
	workers: number;
};
export class ViewerApi {
	constructor(private readonly request: typeof fetch = (input, init) => fetch(input, init)) {}
	getTestCatalog<T>(): Promise<T> {
		return this.json("/api/test-catalog");
	}
	listExecutions<T>(): Promise<T> {
		return this.json("/api/executions");
	}
	getExecution<T>(id: string): Promise<T> {
		return this.json(`/api/executions/${id}`);
	}
	startExecution<T>(testId: string, workers = 1): Promise<T> {
		return this.start<T>({ testId, workers });
	}
	startTestGroup<T>(testIds: string[], workers = 1): Promise<T> {
		return this.start<T>({ testIds, workers });
	}
	startSuiteExecution<T>(workers = 1): Promise<T> {
		return this.start<T>({ all: true, workers });
	}
	cancelExecution<T>(id: string): Promise<T> {
		return this.json(`/api/executions/${id}/cancel`, { method: "POST" });
	}
	private start<T>(body: ExecutionRequest): Promise<T> {
		return this.json("/api/executions", {
			method: "POST",
			headers: { "content-type": "application/json" },
			body: JSON.stringify(body),
		});
	}
	private async json<T>(path: string, init?: RequestInit): Promise<T> {
		const response = await this.request(path, init);
		if (!response.ok) throw new Error(`Request failed: ${response.status}`);
		return response.json() as Promise<T>;
	}
}
export const viewerApi = new ViewerApi();
