import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

type HelloMessage = { payload: { properties: { protocol: { const: number } } } };
type AsyncApi = { channels: Record<string, { messages: Record<string, HelloMessage> }> };

const source = resolve("contracts/viewer.asyncapi.json");
const target = resolve("src/viewer/generated-contracts.ts");
const apiSource = resolve("contracts/viewer.openapi.json");
const apiTarget = resolve("src/viewer/generated-api.ts");
const document = JSON.parse(await readFile(source, "utf8")) as AsyncApi;
const protocol = document.channels["/api/live"]?.messages.hello?.payload.properties.protocol.const;
if (!Number.isInteger(protocol) || protocol < 1)
	throw new Error("AsyncAPI hello protocol must be a positive integer");

const generated = `// Generated by scripts/generate-viewer-contracts.ts from contracts/viewer.asyncapi.json.\nimport { z } from "zod/v4";\n\nexport const VIEWER_PROTOCOL_VERSION = ${protocol};\nexport const viewerClientMessage = z.discriminatedUnion("type", [\n\tz.object({\n\t\ttype: z.literal("hello"),\n\t\tprotocol: z.number().int().positive(),\n\t\tsubscriptions: z.array(z.enum(["catalog", "executions"])),\n\t\tcursors: z.record(z.string(), z.number().int().nonnegative()).default({}),\n\t}),\n]);\nexport type ViewerClientMessage = z.output<typeof viewerClientMessage>;\n`;
await writeFile(target, generated);
const openapi = JSON.parse(await readFile(apiSource, "utf8")) as { openapi?: string };
if (openapi.openapi !== "3.1.0") throw new Error("OpenAPI document must use 3.1.0");
await writeFile(
	apiTarget,
	`// Generated by scripts/generate-viewer-contracts.ts from contracts/viewer.openapi.json.\ntype ExecutionRequest = ({ testId: string } | { testIds: string[] } | { all: true }) & { workers: number };\nexport class ViewerApi {\n\tconstructor(private readonly request: typeof fetch = (input, init) => fetch(input, init)) {}\n\tgetTestCatalog<T>(): Promise<T> {\n\t\treturn this.json("/api/test-catalog");\n\t}\n\tlistExecutions<T>(): Promise<T> {\n\t\treturn this.json("/api/executions");\n\t}\n\tgetExecution<T>(id: string): Promise<T> {\n\t\treturn this.json(\`/api/executions/\${id}\`);\n\t}\n\tstartExecution<T>(testId: string, workers = 1): Promise<T> {\n\t\treturn this.start<T>({ testId, workers });\n\t}\n\tstartTestGroup<T>(testIds: string[], workers = 1): Promise<T> {\n\t\treturn this.start<T>({ testIds, workers });\n\t}\n\tstartSuiteExecution<T>(workers = 1): Promise<T> {\n\t\treturn this.start<T>({ all: true, workers });\n\t}\n\tcancelExecution<T>(id: string): Promise<T> {\n\t\treturn this.json(\`/api/executions/\${id}/cancel\`, { method: "POST" });\n\t}\n\tprivate start<T>(body: ExecutionRequest): Promise<T> {\n\t\treturn this.json("/api/executions", {\n\t\t\tmethod: "POST",\n\t\t\theaders: { "content-type": "application/json" },\n\t\t\tbody: JSON.stringify(body),\n\t\t});\n\t}\n\tprivate async json<T>(path: string, init?: RequestInit): Promise<T> {\n\t\tconst response = await this.request(path, init);\n\t\tif (!response.ok) throw new Error(\`Request failed: \${response.status}\`);\n\t\treturn response.json() as Promise<T>;\n\t}\n}\nexport const viewerApi = new ViewerApi();\n`,
);
